# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - echo "Building the project..."
      - go build -o ./tmp/main tex
    desc: "Build the text2n4l-web project"
    silent: true

  n4l-build:
    dir: n4l
    cmds:
      - task build
    desc: "Build the N4L package"

  n4l-test:
    dir: n4l
    cmds:
      - task test
    desc: "Test the N4L package"

  n4l-clean:
    dir: n4l
    cmds:
      - task clean
    desc: "Clean N4L build artifacts"
