# Config file for Air live reload
root = "."

[build]
  cmd = "make build"
  bin = "bin/n4l-web"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["bin", "testdata", "tests", "SSTconfig"]
  exclude_file = []
  delay = 1000
  log = "tmp/air.log"
  send_interrupt = true
  kill_delay = 500

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[run]
  cmd = "bin/n4l-web"
  args = []
  env = ["AIR_ENV=dev"]
  log = "tmp/air-run.log"

[misc]
  clean_on_exit = true
